name: Unit Tests
permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get dependencies
      run: go mod download

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Display coverage
      run: go tool cover -func=coverage.out
